source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'Example' do
  use_frameworks!
pod 'MQTTClient', :git => 'https://github.com/insignificance/MQTT-Client-Framework', :tag => '0.15.4'
end

target 'UITests' do
end

