source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

target 'MQTTClientmacOS' do
	pod 'SocketRocket', '0.5.1'
	pod 'MQTTClient' , :git => 'https://github.com/insignificance/MQTT-Client-Framework.git', :tag => '0.15.4'
    
    target 'MQTTClientmacOSTests' do
        inherit! :search_paths
    end
end

target 'MQTTClientiOS' do
    pod 'MQTTClient' , :git => 'https://github.com/insignificance/MQTT-Client-Framework.git', :tag => '0.15.4'
    pod 'SocketRocket', '0.5.1'
    
    target 'MQTTClientiOSTests' do
        inherit! :search_paths
    end
end

target 'MQTTClienttvOS' do
    pod 'SocketRocket', '0.5.1'
    pod 'MQTTClient' , :git => 'https://github.com/insignificance/MQTT-Client-Framework.git', :tag => '0.15.4'	
    target 'MQTTClienttvOSTests' do
        inherit! :search_paths
    end
end
